### ISSUE TITLE
currency: "USD"

### ISSUE THREAD

**Issue by Sun3** [marcoscaceres/jsi18n#13]
Is there a way to query for the local currency code like 'USD' or 'EUR' depending on the user's locale instead of manually picking it?

Thanks

**Comment by marcoscaceres** [comment]
I don't think so. You need to ask the user, as it's privacy sensitive information (or try to guess using a geo-ip lookup service).

**Comment by Sun3** [comment]
In Angular 4 in Typescript I am using below to get the current language. I was hoping from the current Language to lookup the Currency Code.

```
let userLang = navigator.language;
```

Thanks...

**Comment by marcoscaceres** [comment]
Unfortunately, that's not possible because of the way the API is designed. The API doesn't know how to associate currency codes with language-tags: only knows how to translate a code into a language - hence you always need to provide the currency code ahead of time:

```JS
const formatter = new Intl.NumberFormat("en-ca", {
  style: "currency",
  currency: "USD", 
  currencyDisplay: "name"
}); 

// "1.00 US dollars"
formatter.format(1);
```
