### ISSUE TITLE
Any way of customizing locales?

### ISSUE THREAD

**Issue by thedamon** [marcoscaceres/jsi18n#14]
I really like using the standard and this one is awesome, There are two cases that have come up for me:

1. I need to use the &minus;/\u2212 character for negative currency amounts and switch the location of the hyphen: $−5) in order for VoiceOver for mac to recognize it as negative
2. We have a weird request to print month shortforms as "Jan." "Feb." "May" "Sept." etccc ?.

Wondering if there's any reasonable way to do this using the standard i18n api and tbh I find all the docs for it (mdn, the spec etc) reaaaaaally confusing.

**Comment by marcoscaceres** [comment]
@thedamon, did you manage to work these out? 

For 1, that sounds like a bug with VoiceOver :( 

For 2, at least:

```JS
var shortMonth = new Intl.DateTimeFormat("en-US", {month: "short"})
var date = new Date();
shortMonth.format(date);
```

**Comment by thedamon** [comment]
Yeah.. it is a bug w VoiceOver.. but since our sites have to work with screenreaders we're just gonna have to put a moratorium on negative currency.

for #2 it's specific in that months have a dot after them and certain months are 4 characters instead of 3. I was just hoping for a way to customize a locale based on the business people being particularly pedantic.. since that happens in real life unfortunately (like in moment.. you can build your own locale if you want with specific options).. that's not really an issue with this library, though, since the API as far as I know doesn't allow this.

**Comment by marcoscaceres** [comment]
I see. I wish they had made it possible to provide custom formatters for all types.
